#!/usr/bin/env ksh
set -vx

function print_gnulinux_builtin_header
{
# Make sure to use \\ instead of \ for continuations
cat <<ENDOFTEXT
/***********************************************************************
*                                                                      *
*               This software is part of the ast package               *
*          Copyright (c) 2006-2015 AT&T Intellectual Property          *
*                      and is licensed under the                       *
*                 Eclipse Public License, Version 1.0                  *
*                    by AT&T Intellectual Property                     *
*                                                                      *
*                A copy of the License is available at                 *
*          http://www.eclipse.org/org/documents/epl-v10.html           *
*         (with md5 checksum b35adb5213ca9657e911e9befb180842)         *
*                                                                      *
*              Information and Software Systems Research               *
*                            AT&T Research                             *
*                           Florham Park NJ                            *
*                                                                      *
*               Roland Mainz <roland.mainz@nrubsig.org>                *
*                                                                      *
***********************************************************************/

#ifndef _GNULINUX_KSH_CMDLIST_H
#define        _GNULINUX_KSH_CMDLIST_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * List builtins for Linux.
 * The list here is partially autogenerated and partially hand-picked
 * based on compatibility with the native GNU coreutils versions of
 * these tools
 */

/* GNU coreutils compatible commands.
 * Be careful, some are in /bin while others are in /usr/bin
 */
#define	ASTCMDLIST(f)		{ "/usr/ast/bin/"	#f,	NV_BLTIN|NV_BLTINOPT|NV_NOFREE, bltin(f) },
#define	BINCMDLIST(f)		{ "/bin/"		#f,	NV_BLTIN|NV_BLTINOPT|NV_NOFREE, bltin(f) },
#define	USRBINCMDLIST(f)	{ "/usr/bin/"		#f,	NV_BLTIN|NV_BLTINOPT|NV_NOFREE, bltin(f) },

/* undo ast_map.h #defines to avoid collision */
#undef basename
#undef chmod
#undef chown
#undef dirname
#undef mkdir
#undef mkfifo
#undef mktemp
#undef readlink
#undef realpath
#undef rmdir


/* Generated data, do not edit. */
USRBINCMDLIST(basename)
USRBINCMDLIST(cksum)
USRBINCMDLIST(comm)
USRBINCMDLIST(cut)
USRBINCMDLIST(dirname)
USRBINCMDLIST(expr)
USRBINCMDLIST(fold)
USRBINCMDLIST(join)
USRBINCMDLIST(logname)
BINCMDLIST(mkdir)
USRBINCMDLIST(mkfifo)
BINCMDLIST(mktemp)
USRBINCMDLIST(paste)
USRBINCMDLIST(pathchk)
USRBINCMDLIST(rev)
BINCMDLIST(rmdir)
BINCMDLIST(sleep)
BINCMDLIST(sync)
USRBINCMDLIST(tee)
USRBINCMDLIST(tty)
USRBINCMDLIST(uniq)
USRBINCMDLIST(wc)

/* Mandatory for ksh93 test suite and AST scripts */
USRBINCMDLIST(getconf)

ASTCMDLIST(basename)
ASTCMDLIST(cat)
ASTCMDLIST(chgrp)
ASTCMDLIST(chmod)
ASTCMDLIST(chown)
ASTCMDLIST(cksum)
ASTCMDLIST(cmp)
ASTCMDLIST(comm)
ASTCMDLIST(cp)
ASTCMDLIST(cut)
ASTCMDLIST(date)
ASTCMDLIST(dirname)
USRBINCMDLIST(egrep)
BINCMDLIST(egrep)
ASTCMDLIST(egrep)
ASTCMDLIST(expr)
ASTCMDLIST(fds)
USRBINCMDLIST(fgrep)
BINCMDLIST(fgrep)
ASTCMDLIST(fgrep)
ASTCMDLIST(fmt)
ASTCMDLIST(fold)
USRBINCMDLIST(grep)
BINCMDLIST(grep)
ASTCMDLIST(grep)
ASTCMDLIST(head)
ASTCMDLIST(id)
USRBINCMDLIST(iconv)
ASTCMDLIST(iconv)
ASTCMDLIST(join)
ASTCMDLIST(ln)
ASTCMDLIST(logname)
ASTCMDLIST(ls)
ASTCMDLIST(md5sum)
USRBINCMDLIST(md5sum)
ASTCMDLIST(mkdir)
ASTCMDLIST(mkfifo)
ASTCMDLIST(mktemp)
ASTCMDLIST(mv)
ASTCMDLIST(paste)
ASTCMDLIST(pathchk)
ASTCMDLIST(pids)
USRBINCMDLIST(od)
ASTCMDLIST(od)
USRBINCMDLIST(readlink)
ASTCMDLIST(readlink)
USRBINCMDLIST(realpath)
ASTCMDLIST(realpath)
ASTCMDLIST(rev)
ASTCMDLIST(rm)
ASTCMDLIST(rmdir)
ASTCMDLIST(stty)
ASTCMDLIST(sha1sum)
USRBINCMDLIST(sha1sum)
ASTCMDLIST(sha256sum)
USRBINCMDLIST(sha256sum)
ASTCMDLIST(sha384sum)
USRBINCMDLIST(sha384sum)
ASTCMDLIST(sha512sum)
USRBINCMDLIST(sha512sum)
ASTCMDLIST(sum)
ASTCMDLIST(sync)
ASTCMDLIST(tail)
ASTCMDLIST(tee)
USRBINCMDLIST(tr)
ASTCMDLIST(tr)
ASTCMDLIST(tty)
ASTCMDLIST(uname)
ASTCMDLIST(uniq)
ASTCMDLIST(vmstate)
ASTCMDLIST(wc)
// ASTCMDLIST(xgrep)
USRBINCMDLIST(xargs)
ASTCMDLIST(xargs)

#ifdef __cplusplus
}
#endif

#endif /* !_GNULINUX_KSH_CMDLIST_H */
ENDOFTEXT
	return 0
}
print_gnulinux_builtin_header > tmp_gnulinux_builtin_header.h
export USE_CLANG=yes
export CC="clang-6.0"
export CCFLAGS=' -m64 -fPIC -std=gnu99 -D_GNU_SOURCE=1 -D__USE_GNU=1 -D_BLD_DLL -D_BLD_ast=1 -D_PACKAGE_ast=1 -D_astimport=1 -D_lib_unlink=1 -D_hdr_mmap=1 -D_hdr_fnctl=1 -D_BLD_cmd -Dvt_threaded=1 -DSHOPT_FS_3D=1 -DSHOPT_KIA=1 -DSHOPT_SYSRC -DSHOPT_CMDLIB_BLTIN=1 -DSHOPT_CMDLIB_DIR=/usr/ast/bin -DSHOPT_CMDLIB_HDR=/home/rlatimore/src/git/ast-open/tmp_gnulinux_builtin_header.h -D_map_libc=1 -DSHOPT_OPTIMIZE=1 -DSHOPT_BASH=1 -fno-omit-frame-pointer -fstrict-aliasing -Wstrict-aliasing -fstrict-overflow -Wstrict-overflow -Wsequence-point -Wno-parentheses -Wno-unused -Wno-trigraphs -Wuninitialized -Waddress -Wmissing-variable-declarations -fdiagnostics-fixit-info -fdiagnostics-print-source-range-info -fdiagnostics-show-category=name -fcolor-diagnostics -fdiagnostics-absolute-paths -fdiagnostics-show-option -fcaret-diagnostics -fms-extensions'
export CXX=clang++
export HOSTTYPE=linux.i386-64
export SHELL=/opt/ast/bin/ksh
export COSHELL=/opt/ast/bin/ksh
export PACKAGEROOT="${HOME}/src/git/ast-open"
export PATH="${PWD}/bin:${PATH}"


print "Building debug version..."
#bin/libast_prereq.sh

#time /opt/ast/bin/ksh "${PACKAGEROOT}/bin/package" make ast-ast PACKAGE_OPTIONS=map-libc CCFLAGS=" -v -glldb -g -fno-builtin -O0 ${CCFLAGS}" CC=${CC} HOSTTYPE=${HOSTTYPE} INSTALLROOT="${PACKAGEROOT}/arch/${HOSTTYPE}" SHELL=/opt/ast/bin/ksh
/bin/sh "${PACKAGEROOT}/bin/package" make ast-make PACKAGE_OPTIONS=map-libc CCFLAGS="-v -glldb -g -fno-builtin -O0 ${CCFLAGS}" CC=${CC} CC.HOSTTYPE="${HOSTTYPE}" HOSTTYPE=${HOSTTYPE} INSTALLROOT="${PACKAGEROOT}/arch/${HOSTTYPE}" SHELL=/opt/ast/bin/ksh
#print "Building optimized version..."
#time /opt/ast/bin/ksh "${HOME}/src/git/ast-open/bin/package" make ast-open PACKAGE_OPTIONS='map-libc' CCFLAGS="${CCFLAGS}" CC="${CC} -O2" HOSTTYPE="${HOSTTYPE}" SHELL='/opt/ast/bin/ksh'

#time /opt/ast/bin/ksh "${HOME}/src/git/ast-open/bin/package" make ast-ast PACKAGE_OPTIONS='map-libc' CCFLAGS="${CCFLAGS}" CC="${CC}" HOSTTYPE="${HOSTTYPE}" SHELL='/opt/ast/bin/ksh'
