/***********************************************************************
 *                                                                      *
 *               This software is part of the ast package               *
 *          Copyright (c) 2006-2015 AT&T Intellectual Property          *
 *                      and is licensed under the                       *
 *                 Eclipse Public License, Version 1.0                  *
 *                    by AT&T Intellectual Property                     *
 *                                                                      *
 *                A copy of the License is available at                 *
 *          http://www.eclipse.org/org/documents/epl-v10.html           *
 *         (with md5 checksum b35adb5213ca9657e911e9befb180842)         *
 *                                                                      *
 *              Information and Software Systems Research               *
 *                            AT&T Research                             *
 *                           Florham Park NJ                            *
 *                                                                      *
 *               Roland Mainz <roland.mainz@nrubsig.org>                *
 *                                                                      *
 ***********************************************************************/

#ifndef _GNULINUX_KSH_CMDLIST_H
#define _GNULINUX_KSH_CMDLIST_H

#ifdef __cplusplus
extern "C" {
#endif

/*
 * List builtins for Linux.
 * The list here is partially autogenerated and partially hand-picked
 * based on compatibility with the native GNU coreutils versions of
 * these tools
 */

/* GNU coreutils compatible commands.
 * Be careful, some are in /bin while others are in /usr/bin
 */
#define ASTCMDLIST(f) \
	{ "/usr/ast/bin/" #f, NV_BLTIN | NV_BLTINOPT | NV_NOFREE, bltin(f) },
#define BINCMDLIST(f) \
	{ "/bin/" #f, NV_BLTIN | NV_BLTINOPT | NV_NOFREE, bltin(f) },
#define USRBINCMDLIST(f) \
	{ "/usr/bin/" #f, NV_BLTIN | NV_BLTINOPT | NV_NOFREE, bltin(f) },

/* undo ast_map.h #defines to avoid collision */
#undef basename
#undef chmod
#undef chown
#undef dirname
#undef mkdir
#undef mkfifo
#undef mktemp
#undef readlink
#undef realpath
#undef rmdir


/* Generated data, do not edit. */
USRBINCMDLIST(basename)
USRBINCMDLIST(cksum)
USRBINCMDLIST(comm)
USRBINCMDLIST(cut)
USRBINCMDLIST(dirname)
USRBINCMDLIST(expr)
USRBINCMDLIST(fold)
USRBINCMDLIST(join)
USRBINCMDLIST(logname)
BINCMDLIST(mkdir)
USRBINCMDLIST(mkfifo)
BINCMDLIST(mktemp)
USRBINCMDLIST(paste)
USRBINCMDLIST(pathchk)
USRBINCMDLIST(rev)
BINCMDLIST(rmdir)
BINCMDLIST(sleep)
BINCMDLIST(sync)
USRBINCMDLIST(tee)
USRBINCMDLIST(tty)
USRBINCMDLIST(uniq)
USRBINCMDLIST(wc)

/* Mandatory for ksh93 test suite and AST scripts */
USRBINCMDLIST(getconf)

ASTCMDLIST(basename)
ASTCMDLIST(cat)
ASTCMDLIST(chgrp)
ASTCMDLIST(chmod)
ASTCMDLIST(chown)
ASTCMDLIST(cksum)
ASTCMDLIST(cmp)
ASTCMDLIST(comm)
ASTCMDLIST(cp)
ASTCMDLIST(cut)
ASTCMDLIST(date)
ASTCMDLIST(dirname)
USRBINCMDLIST(egrep)
BINCMDLIST(egrep)
ASTCMDLIST(egrep)
ASTCMDLIST(expr)
ASTCMDLIST(fds)
USRBINCMDLIST(fgrep)
BINCMDLIST(fgrep)
ASTCMDLIST(fgrep)
ASTCMDLIST(fmt)
ASTCMDLIST(fold)
USRBINCMDLIST(grep)
BINCMDLIST(grep)
ASTCMDLIST(grep)
ASTCMDLIST(head)
ASTCMDLIST(id)
USRBINCMDLIST(iconv)
ASTCMDLIST(iconv)
ASTCMDLIST(join)
ASTCMDLIST(ln)
ASTCMDLIST(logname)
ASTCMDLIST(ls)
ASTCMDLIST(md5sum)
USRBINCMDLIST(md5sum)
ASTCMDLIST(mkdir)
ASTCMDLIST(mkfifo)
ASTCMDLIST(mktemp)
ASTCMDLIST(mv)
ASTCMDLIST(paste)
ASTCMDLIST(pathchk)
ASTCMDLIST(pids)
USRBINCMDLIST(od)
ASTCMDLIST(od)
USRBINCMDLIST(readlink)
ASTCMDLIST(readlink)
USRBINCMDLIST(realpath)
ASTCMDLIST(realpath)
ASTCMDLIST(rev)
ASTCMDLIST(rm)
ASTCMDLIST(rmdir)
ASTCMDLIST(stty)
ASTCMDLIST(sha1sum)
USRBINCMDLIST(sha1sum)
ASTCMDLIST(sha256sum)
USRBINCMDLIST(sha256sum)
ASTCMDLIST(sha384sum)
USRBINCMDLIST(sha384sum)
ASTCMDLIST(sha512sum)
USRBINCMDLIST(sha512sum)
ASTCMDLIST(sum)
ASTCMDLIST(sync)
ASTCMDLIST(tail)
ASTCMDLIST(tee)
USRBINCMDLIST(tr)
ASTCMDLIST(tr)
ASTCMDLIST(tty)
ASTCMDLIST(uname)
ASTCMDLIST(uniq)
ASTCMDLIST(vmstate)
ASTCMDLIST(wc)
// ASTCMDLIST(xgrep)
USRBINCMDLIST(xargs)
ASTCMDLIST(xargs)

#ifdef __cplusplus
}
#endif

#endif /* !_GNULINUX_KSH_CMDLIST_H */
