/* : : generated by conf from
 * /home/rlatimore/src/git/ast-open/src/lib/libast/comp/conf.tab : : */

/*
 * supplemental <limits.h> values
 */

printf("#ifndef LONG_MAX\n");
printf("#define LONG_MAX 2147483647\n");
printf("#endif\n");
printf("#ifndef LONG_MIN\n");
printf("#define LONG_MIN -2147483647\n");
printf("#endif\n");
printf("#ifndef PTRDIFF_MAX\n");
printf("#define PTRDIFF_MAX 65535\n");
printf("#endif\n");
printf("#ifndef PTRDIFF_MIN\n");
printf("#define PTRDIFF_MIN -65535\n");
printf("#endif\n");
printf("#ifndef SIZE_MAX\n");
printf("#ifndef UINT_MAX\n");
printf("#define UINT_MAX %lu\n", ( unsigned long )(UINT_MAX));
printf("#endif\n");
printf("#define SIZE_MAX UINT_MAX\n");
printf("#endif\n");
printf("#ifndef SSIZE_MAX\n");
printf("#ifndef INT_MAX\n");
printf("#define INT_MAX %ld\n", ( long )(INT_MAX));
printf("#endif\n");
printf("#define SSIZE_MAX INT_MAX\n");
printf("#endif\n");
